import type { PortfolioProject } from "@/lib/types";

const baseWorks = {
  web: [
    {
      en: "UX research and information architecture",
      ru: "UX-исследование и информационная архитектура",
      hy: "UX հետազոտություն և տեղեկատարական ճարտարապետություն",
      it: "Ricerca UX e architettura informativa",
    },
    {
      en: "UI design and responsive layouts",
      ru: "UI-дизайн и адаптивная вёрстка",
      hy: "UI դիզայն և responsive դասավորություններ",
      it: "UI design e layout responsive",
    },
    {
      en: "Front-end development and launch",
      ru: "Front-end разработка и запуск",
      hy: "Front-end մշակում և գործարկում",
      it: "Sviluppo front-end e lancio",
    },
  ],
  app: [
    {
      en: "Mobile app UX and UI design",
      ru: "UX/UI мобильного приложения",
      hy: "Բջջային հավելվածի UX/UI դիզայն",
      it: "UX/UI app mobile",
    },
    {
      en: "Cross-platform development",
      ru: "Кроссплатформенная разработка",
      hy: "Cross-platform մշակում",
      it: "Sviluppo cross-platform",
    },
  ],
};

export const portfolioProjects: PortfolioProject[] = [
  {
    slug: "grand-candy",
    client: "Grand Candy",
    clientLogo: "/logos/clients/grand-candy.png",
    coverImage: "/portfolio/covers/grand-candy.gif",
    coverAnimated: true,
    category: "manufacturing",
    tags: ["UI/UX", "APP", "Web"],
    title: {
      en: "Website & Mobile App",
      ru: "Сайт и мобильное приложение",
      hy: "Կայք և բջջային հավելված",
      it: "Sito web e app mobile",
    },
    description: {
      en: "Digital ecosystem for Armenia's leading confectionery brand — e-commerce, product catalog, and mobile app for loyal customers.",
      ru: "Digital-экосистема для ведущего кондитерского бренда Армении — e-commerce, каталог продукции и мобильное приложение.",
      hy: "Թվային էկոհամակարգ Հայաստանի առաջատար կոնդիտերական ապրանքանիշի համար՝ e-commerce, կատալոգ և հավելված։",
      it: "Ecosistema digitale per il brand dolciario leader in Armenia — e-commerce, catalogo e app.",
    },
    works: [...baseWorks.web, ...baseWorks.app],
    results: [
      {
        en: "Unified brand experience across web and app",
        ru: "Единый brand experience в web и app",
        hy: "Միասնական brand experience web-ում և app-ում",
        it: "Esperienza brand unificata su web e app",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-rose-500 to-red-800",
    featured: true,
  },
  {
    slug: "erebuni-medical",
    client: "Erebuni Medical Center",
    clientLogo: "/logos/clients/erebuni.png",
    coverImage: "/portfolio/covers/erebuni-medical.gif",
    coverAnimated: true,
    category: "commercial",
    tags: ["UI/UX", "APP", "Web"],
    title: {
      en: "Website & Patient App",
      ru: "Сайт и приложение для пациентов",
      hy: "Կայք և հիվանդների հավելված",
      it: "Sito e app per pazienti",
    },
    description: {
      en: "Healthcare platform with appointment booking, doctor profiles, lab results, and a patient mobile app.",
      ru: "Медицинская платформа: запись к врачу, профили специалистов, анализы и мобильное приложение для пациентов.",
      hy: "Բժշկական հարթակ՝ գրանցում, բժիշկների պրոֆիլներ, անալիզներ և հիվանդների հավելված։",
      it: "Piattaforma healthcare con prenotazioni, profili medici e app pazienti.",
    },
    works: [...baseWorks.web, ...baseWorks.app],
    results: [
      {
        en: "Streamlined online appointment flow",
        ru: "Упрощённый онлайн-запись на приём",
        hy: "Պարզեցված օնլայն գրանցում",
        it: "Flusso appuntamenti online semplificato",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-sky-500 to-blue-900",
  },
  {
    slug: "astghik-medical",
    client: "Astghik Medical Center",
    coverImage: "/portfolio/covers/astghik-medical.gif",
    coverAnimated: true,
    category: "commercial",
    tags: ["UI/UX", "APP", "Web"],
    title: {
      en: "Website & Medical App",
      ru: "Сайт и медицинское приложение",
      hy: "Կայք և բժշկական հավելված",
      it: "Sito e app medica",
    },
    description: {
      en: "Modern medical center digital presence — services, specialists, online booking, and mobile access for patients.",
      ru: "Современный digital для медцентра — услуги, специалисты, онлайн-запись и мобильный доступ для пациентов.",
      hy: "Ժամանակակից բժշկական կենտրոնի թվային ներկայություն՝ ծառայություններ, մասնագետներ, օնլայն գրանցում։",
      it: "Presenza digitale per centro medico — servizi, specialisti e prenotazioni online.",
    },
    works: [...baseWorks.web, ...baseWorks.app],
    results: [
      {
        en: "Clear patient journey from discovery to booking",
        ru: "Понятный путь пациента от знакомства до записи",
        hy: "Հստակ հիվանդի ճանապարհ՝ հայտնի լինելուց մինչև գրանցում",
        it: "Percorso paziente chiaro dalla scoperta alla prenotazione",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-teal-500 to-cyan-900",
  },
  {
    slug: "coffeeshop",
    client: "COFFEESHOP Company",
    clientLogo: "/logos/clients/coffeeshop.png",
    coverImage: "/portfolio/covers/coffeeshop.gif",
    coverAnimated: true,
    category: "restaurants",
    tags: ["UI/UX", "Web"],
    title: {
      en: "Coffee Brand Website",
      ru: "Сайт кофейного бренда",
      hy: "Սուրճի ապրանքանիշի կայք",
      it: "Sito del brand caffè",
    },
    description: {
      en: "Premium coffee brand website — product lines, café locations, brand story, and B2B wholesale inquiry flows.",
      ru: "Сайт премиального кофейного бренда — линейки продуктов, локации, история бренда и B2B-заявки.",
      hy: "Պրեմիում սուրճի ապրանքանիշի կայք՝ արտադրանք, կետեր, բրենդի պատմություն և B2B հարցումներ։",
      it: "Sito premium del brand caffè — prodotti, location e flussi B2B.",
    },
    works: baseWorks.web,
    results: [
      {
        en: "Elevated brand storytelling online",
        ru: "Усиленный brand storytelling онлайн",
        hy: "Ուժեղացված brand storytelling օնլայն",
        it: "Storytelling del brand rafforzato online",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-amber-700 to-stone-900",
  },
  {
    slug: "gotcha",
    client: "Gotcha",
    clientLogo: "/logos/clients/gotcha.svg",
    coverImage: "/portfolio/covers/gotcha.gif",
    coverAnimated: true,
    category: "restaurants",
    tags: ["UI/UX", "Web"],
    title: {
      en: "Restaurant & Delivery Website",
      ru: "Сайт ресторана и доставки",
      hy: "Ռեստորանի և առաքման կայք",
      it: "Sito ristorante e delivery",
    },
    description: {
      en: "Vibrant food brand website with menu, locations, delivery integration, and conversion-focused UX.",
      ru: "Яркий сайт food-бренда — меню, филиалы, доставка и UX с фокусом на конверсию.",
      hy: "Վառ food-brand կայք՝ մենյու, մասնաճյուղեր, առաքում և conversion-կենտրոնացված UX։",
      it: "Sito food brand vivace con menu, sedi e UX orientata alla conversione.",
    },
    works: baseWorks.web,
    results: [
      {
        en: "Higher engagement on menu and order pages",
        ru: "Рост вовлечённости на страницах меню и заказа",
        hy: "Ավելի բարձր engagement մենյուի և պատվերի էջերում",
        it: "Maggiore engagement su menu e ordini",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-orange-500 to-red-700",
  },
  {
    slug: "reebok-sports-club",
    client: "Reebok Sports Club",
    clientLogo: "/logos/clients/reebok.png",
    coverImage: "/portfolio/covers/reebok.gif",
    coverAnimated: true,
    category: "commercial",
    tags: ["UI/UX", "Web"],
    title: {
      en: "Sports Club Website",
      ru: "Сайт спортивного клуба",
      hy: "Սպորտային ակումբի կայք",
      it: "Sito del club sportivo",
    },
    description: {
      en: "Dynamic website for a premium fitness club — schedules, memberships, trainers, and class booking.",
      ru: "Динамичный сайт фитнес-клуба — расписание, абонементы, тренеры и запись на занятия.",
      hy: "Դինամիկ կայք ֆիտնես ակումբի համար՝ ժամանակացույց, անդամություն, մարզիչներ, գրանցում։",
      it: "Sito dinamico per fitness club — orari, abbonamenti e prenotazioni.",
    },
    works: baseWorks.web,
    results: [
      {
        en: "Improved membership inquiry conversion",
        ru: "Рост конверсии в заявки на абонемент",
        hy: "Անդամության հարցումների conversion-ի աճ",
        it: "Migliore conversione richieste abbonamento",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-slate-700 to-slate-950",
  },
  {
    slug: "umami",
    client: "UMAMI",
    coverImage: "/portfolio/covers/umami.gif",
    coverAnimated: true,
    category: "restaurants",
    tags: ["UI/UX", "Web"],
    title: {
      en: "Restaurant Website",
      ru: "Сайт ресторана",
      hy: "Ռեստորանի կայք",
      it: "Sito ristorante",
    },
    description: {
      en: "Elegant restaurant website — menu presentation, reservations, ambiance photography, and event catering.",
      ru: "Элегантный сайт ресторана — меню, бронирование, атмосферные фото и кейтеринг.",
      hy: "Նրբագեղ ռեստորանի կայք՝ մենյու, ամրագրում, լուսանկարներ և կեյտերինգ։",
      it: "Sito elegante per ristorante — menu, prenotazioni e catering.",
    },
    works: baseWorks.web,
    results: [
      {
        en: "Premium visual identity reflected online",
        ru: "Премиальная визуальная идентичность в digital",
        hy: "Պրեմիում վիզուալ իդենտիկություն թվային միջավայրում",
        it: "Identità visiva premium riflessa online",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-emerald-600 to-green-950",
  },
  {
    slug: "yell",
    client: "Yell Armenia",
    clientLogo: "/logos/clients/yell.png",
    coverImage: "/portfolio/covers/yell.gif",
    coverAnimated: true,
    category: "web",
    tags: ["UI/UX", "Soft", "Web"],
    title: {
      en: "Armenia Business Directory",
      ru: "Справочник бизнеса Армении",
      hy: "Հայաստանի բիզնես տեղեկատու",
      it: "Directory business Armenia",
    },
    description: {
      en: "Large-scale directory platform — company listings, search, categories, maps, and admin tools for content management.",
      ru: "Крупный справочник — каталог компаний, поиск, категории, карты и админка для управления контентом.",
      hy: "Խոշոր տեղեկատու հարթակ՝ ընկերությունների ցանկ, որոնում, կատեգորիաներ, քարտեզներ և ադմինիստրացիա։",
      it: "Piattaforma directory — elenchi aziende, ricerca, categorie e mappe.",
    },
    works: [
      ...baseWorks.web,
      {
        en: "Search, filters, and directory architecture",
        ru: "Поиск, фильтры и архитектура справочника",
        hy: "Որոնում, ֆիլտրեր և տեղեկատարի ճարտարապետություն",
        it: "Ricerca, filtri e architettura directory",
      },
    ],
    results: [
      {
        en: "Scalable catalog for thousands of listings",
        ru: "Масштабируемый каталог на тысячи компаний",
        hy: "Մասշտաբային կատալոգ հազարավոր գրառումների համար",
        it: "Catalogo scalabile per migliaia di voci",
      },
    ],
    country: "AM",
    city: { en: "Yerevan", ru: "Ереван", hy: "Երևան", it: "Yerevan" },
    year: 2023,
    gradient: "from-violet-600 to-purple-950",
  },
];

export const clientLogos = [
  { id: "grand-candy", name: "Grand Candy", logo: "/logos/clients/grand-candy.png", website: "https://grandcandy.am" },
  { id: "erebuni", name: "Erebuni Medical Center", logo: "/logos/clients/erebuni.png", website: "https://www.erebunimed.com" },
  { id: "coffeeshop", name: "COFFEESHOP Company", logo: "/logos/clients/coffeeshop.png" },
  { id: "gotcha", name: "Gotcha", logo: "/logos/clients/gotcha.svg", website: "https://gotcha.am" },
  { id: "reebok", name: "Reebok Sports Club", logo: "/logos/clients/reebok.png" },
  { id: "yell", name: "Yell Armenia", logo: "/logos/clients/yell.png", website: "https://yell.am" },
];

export const portfolioCategories = [
  "all",
  "hotels",
  "restaurants",
  "commercial",
  "manufacturing",
  "malls",
  "web",
  "automation",
] as const;

export function getProject(slug: string) {
  return portfolioProjects.find((p) => p.slug === slug);
}
